name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: "xqms/clang-highlight-wheel"
    steps:
      - uses: actions/checkout@v4
      - name: "Build wheel"
        env:
          LLVM_DIR: /opt/llvm
        run: "uv build"
      - name: "Test"
        run: "uv run --python 3.10 --isolated --no-project --with dist/*.whl python tests/tests.py"
